name: Build Desktop Apps

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Package Windows (no publish)
        if: runner.os == 'Windows' && !startsWith(github.ref, 'refs/tags/')
        run: npx electron-builder --win --publish=never

      - name: Package Windows and publish
        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/')
        run: npx electron-builder --win --publish=always

      - name: Package macOS (no publish)
        if: runner.os == 'macOS' && !startsWith(github.ref, 'refs/tags/')
        run: npx electron-builder --mac --publish=never

      - name: Package macOS and publish
        if: runner.os == 'macOS' && startsWith(github.ref, 'refs/tags/')
        run: npx electron-builder --mac --publish=always

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ido-editor-${{ runner.os }}
          if-no-files-found: error
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
            dist/latest*.yml

  
